# Generated by Django 4.2.7 on 2023-12-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_album_out_of_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_field',
            new_name='first_name',
        ),
    ]
